# Generated by Django 5.1.7 on 2025-06-30 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Noname task', max_length=100, null=True)),
                ('title', models.TextField()),
                ('level_important', models.CharField(blank=True, choices=[('low', 'low priority'), ('midle', 'midle priority'), ('high', 'high priority')], default=('high', 'high priority'), max_length=100, null=True)),
                ('time_start', models.DateTimeField(auto_now=True)),
                ('time_end', models.DateTimeField()),
                ('time_add', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
