# Generated by Django 5.1.7 on 2025-07-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='level_important',
            field=models.CharField(blank=True, choices=[('low', 'low priority'), ('midle', 'midle priority'), ('high', 'high priority')], default=('midle', 'midle priority'), max_length=100, null=True),
        ),
    ]
