# Generated by Django 5.1.7 on 2025-07-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0002_remove_task_title_task_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('man', 'чоловік'), ('woman', 'жінка'), ('other', 'інше')], max_length=100)),
                ('ava', models.URLField()),
            ],
        ),
    ]
