# Generated by Django 5.1.7 on 2025-07-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0008_alter_profile_ava'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ava',
            field=models.FileField(blank=True, null=True, upload_to='ava/'),
        ),
    ]
